import Footer from "@/components/footer";
import Navigation from "@/components/navigation/index";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { montserrat } from "./theme/theme";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: { fontFamily: "__Montserrat_950f46" },
      }}
    >
      <html lang="en">
        <body className="flex flex-col min-h-screen">
          <Navigation />
          <main className="flex-1 flexCenter text-white bg-customBlack p-5">
            {children}
          </main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
