import Footer from "@/components/footer";
import Navigation from "@/components/navigation/index";
import { ThemeProvider } from "./contexts/useTheme";
import ClerkWrapper from "./providers/clerkWrapper";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider>
      <ClerkWrapper>
        <html lang="en">
          <body className="flex flex-col min-h-screen">
            <Navigation />
            <main className="flex-1 flexCenter p-5">{children}</main>
            <Footer />
          </body>
        </html>
      </ClerkWrapper>
    </ThemeProvider>
  );
}
